FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Copy everything
COPY package.json package-lock.json turbo.json ./
COPY apps ./apps
COPY packages ./packages

# Install all dependencies
RUN npm install

# Generate DB client
RUN npm run db:generate

# Build only the user app
RUN npm run build --filter=apps/user-app

# Start the user app
CMD ["npm", "run", "start-user-app"]
